language: groovy
sudo: false
cache:
  directories:
  - $HOME/.gradle
language: groovy
jdk:
- oraclejdk8
before_script:
- rm -rf target
- chmod +x travis-build.sh
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Russell Morrisey"
  - GIT_EMAIL="rmorrise@cscinfo.com"
  - secure: KL4SKsqakRHWQb2SA9B1XOryzAHs8GShTKQao72EJuY+aDSwnH1MKloQt6geXJTp6uznCuGsysTxvIifG7hoS3YF/mugj23jGuNN3+MXQqXRXWikUSEVlBj9yffTl0IYGW2W3nlD8eiXRRZ8ticRv05ZyMfm60nlrveF3MoCdC6x2Xth6KuER3Johpe23hs0/J7pKK6EaHBbfK7L6zVr/F3Ar+TM8HfiBOAne5YODdUE508DpXQt98xNhqb/RjWzIGveATgVjNz3QJIbjiT724PXsXDMsCyfjZXoa7sePPsf3L+vSCesNWdAnzcXFlpWHgk+ouzM5nBxADQn2REj3r0Y9ZDarrT9m+VnraqBlwDaC9am28BrHwq3kBSoqPS+Ggwoq98Jxtm3nhnw2SwGiZisTB4f7GTw95cfj3er5HFOkpu2WRYieQU9j2cIP0iwdlC0Dx5lb3VzGW2Uv2cSD1OEo8Y3EtuBtLPBH/6HQF5DR2khVi7RD4Yg/rgJY+JjfVwlNew6ovmwLKjUZxW7G7RzkHpS8mF1AjtISp1TYW3UA4iAieeLhnZRYuIrA5Mlqal9kFdZ1eVmKNmRAkc1puGy19dAjHMXl1/y8sjhB5RJeDtJHpYxSD/MROpEemjQu5FXm2ECzqtOfOAS8c6iE8Hju4LYKvpiIHj+MChAPxw=
  - secure: cIktdAJS5X46GSfQmYCutOIMnkO3gfRJpMN3ZTEVKSQuCvKx6KE5I11ZZLsbIr16P0ibVhf7TJ/HmW1ncyizdYAZCwWmoyKsDZv7rI89BLzcfedi1bP7uDnXURLf4jkFsDN/yVNssH/tWB5BYuPhr/MPm+KEzrHGRz/SyB5ukyOygskd3ZtNyXXJiP4RY0QUjd+hMAJZbh5BcF0a8kWR4UrkLEJp9HYCD8gG+Sv0gI/Fl5fEdxl9wqYfKfJwEfWksVN2/Ogv1mTGGzchWd8nMFD4f2lRdLe6ifN6AxtCDAR7rR2m3wuP0//UnFXYb0M9QLJxoo9WXBpPsa6NYqagbXT1k41SV6Y036CYrmDdD3tai/r0e8i+C5ViVpRAx6UWVhhtF9q+GHUmj8hy3Y0fZFFDIybv7y6mwBmPcesWjbH0wQ6JMdJTjlU+tExybaiL9BkNFkE+8BNJWc0z5xxgAlIBAcT35UWVAk9c6GuolwjRjzmQz5+05FuAmwy2PWDRJtN+9icEX5mnjIQisF+UOjbFlEb405/8BiJIq9FqEsqnypKPdQrQXPA8B3yv2KPWHrWGD80DmfyQDsAfjKpxBSSEkEripIQcQVGmLdgBUeUwvH3tuMjqtjuJKdqeukrd5p2vYcGuUClR6CEhU6Ag/nvn5xs4h36A/xOHAN6HMYg=
